### ISSUE TITLE
Clarification on libsqlite3-0 package in 18-build but no -dev package

### ISSUE THREAD

**Issue by luislavena** [heroku/stack-images#155]
Hello folks,

Thanks for making the stack images build process publicly available. Currently using this in combination with Buildpacks (`pack`).

When looking at heroku-18 stack and the list of [included packages](https://devcenter.heroku.com/articles/stack-packages), noticed that `libsqlite3-0` (the shared library) is included.

However, `libsqlite3-dev` package, necessary to compile or link against the shared object is missing.

While there is an article covering [why is a bad idea use SQLite3 in Heroku](https://devcenter.heroku.com/articles/sqlite3), the shipping of the shared library makes me wonder about the missing dev counterpart.

Thank you in advance for your response!

Cheers.
❤️ ❤️ ❤️

**Comment by edmorley** [comment]
Hi! 

My understanding is that `libsqlite3-0` is present since certain buildpacks require it at runtime (for example Python's default compile options require sqlite due to the `sqlite3` module being in Python's standard library) - and having those libraries be in the stack-image (as opposed to vendoring in the slug during the Python buildpack compile) reduces slug size and means the standard stack image updates can fix bugs/security issues without needing an app to be re-built.

For the corresponding headers (`libsqlite3-dev`) these are intentionally not included, to make it harder for users to accidentally use sqlite in production apps (for the reasons in the article you found) when using languages where they are not part of the stdlib. For example the Ruby buildpack can then catch the error output when an attempt is made to install the `sqlite3` Ruby gem:
https://github.com/heroku/heroku-buildpack-ruby/blob/249d3c1a4e97068f8fd016f10fa0839709d95658/lib/language_pack/ruby.rb#L896-L903

That said, the inconsistency is something that has come up a few times internally because it means that buildpacks like the Python one have to jump through many more hoops:
https://github.com/heroku/heroku-buildpack-python/blob/7e80ea8fbeb5b1906e41c850ddb9858cbe7119fc/bin/steps/sqlite3

What use-case did you have in mind? :-)

**Comment by luislavena** [comment]
Thank you @edmorley for the response. I was using `pack` and the Heroku docker images to pre-compile binaries for Ruby and fed `sqlite3` blindly into the process 😁 

I think was expecting to see the dev counterpart for sqlite3 in the build image since saw it in the runtime one, but your explanation helps a lot.

The only use case I had for SQLite3 was to perform some quick in-memory SQL calculations, but nothing serious like doing billion records :trollface: 

Thank you once again for your time and your response. Closing this one.
❤️ ❤️ ❤️

**Comment by edmorley** [comment]
It's no trouble at all. Have a great weekend :-)
