### ISSUE TITLE
Question: Heroku-20 general release date

### ISSUE THREAD

**Issue by oehlschl** [heroku/stack-images#181]
Sorry in advance, as I suspect that this is not the best place for this question (but that I also wouldn't find the answer on the Heroku StackExchange and don't have access to Heroku support).

I see that there's an updated `heroku-20` image available but that it's not yet the default image for new apps, per https://devcenter.heroku.com/articles/stack. Do you know when it will become the default, or whether it's in a production-ready state? (The article mentions April of each year for EOLs, but I don't know when these images are typically "released".)

We're in the process of preparing our application for Q4 / Holiday scale and have debated upgrading to the new stack before load-testing. If it's safe (enough) now or will be released generally soon, then we'll start down this path, but otherwise we'll stick with Heroku-18.

Thanks in advance!

**Comment by edmorley** [comment]
@oehlschl Hi! Unfortunately I'm not able to discuss specific timelines, but can give a rough sense of how releases are rolled out.

New stack releases tend to occur in the following stages:
1. internal testing
2. public beta
3. general availability (GA) [ie released and fine for production use, but default stack unchanged so opt-in]
4. made the default stack for new apps

For Heroku-18, steps 2-4 were announced here:
https://devcenter.heroku.com/changelog-items/1414
https://devcenter.heroku.com/changelog-items/1453
https://devcenter.heroku.com/changelog-items/1485

Whilst the Heroku-20 docker image is available on Docker Hub (a side effect of how this repo's releases work / we need the image to then generate binaries for buildpacks etc), Heroku-20 isn't yet in beta, or available as a stack to set on apps (the only available stacks are listed at the Dev Center page you mentioned).

Once a Heroku-20 beta is announced, we would recommend waiting for GA before moving production workloads to it. In addition, since Heroku-18 is supported until April 2023, there is no immediate rush to upgrade.

As such, I would proceed with Heroku-18 for now :-)

**Comment by oehlschl** [comment]
Hi @edmorley -- thanks a lot for the response; that's very helpful.

Given the timing on the Heroku-18 announcements, I thought the Heroku-20 announcements might share a similar timeline (May-September), but your answer makes sense.

We'll proceed with Heroku-18 and keep an eye on https://devcenter.heroku.com/changelog.

Thanks!

**Comment by oehlschl** [comment]
Also, for whatever it's worth, we did a good amount of testing on a Ruby 2.7.1 / Rails 6.0.3 app on Heroku-20.v38 without issue. In case that's helpful at all.

**Comment by edmorley** [comment]
Heroku-20 is now available in beta:
https://devcenter.heroku.com/changelog-items/1937
