### ISSUE TITLE
Purpose/scope of project

### ISSUE THREAD

**Issue by jjb** [heroku/stack-images#30]
Hi,

This looks really useful, but I'm not 100% sure what it is. The heroku stacks have hundreds of packages of specific versions, but in these recipes there are only a few dozen with no version listed. Also, the heroku stacks provide very up-to-date versions of things like ruby, as they are released, and that is not reflected here.

What exactly does this provide? Am I thinking about it wrong and it is in fact the buildpacks which provide the more specific and extended packages?

I'll put in a PR to enhance the readme a bit with whatever knowledge comes out of this thread. Thanks!

John

**Comment by dmathieu** [comment]
Hey John,

It is very unlikely you're going to need to use this repository. It allows us to build new stack images, which are the basis we run dynos on.
Technically, we release a new stack image when we need to upgrade a package version.

The reason our stacks have a lot more packages is because this relies on an ubuntu base, which provides a lot of packages by default. The packages listed here are the one we want to provide additionally.

A stack image will be available to all apps on the platform. So adding a new package that you require there isn't going to be a good solution (and won't be merged in).
If you need to install a custom package, we'd recommend doing that in a custom buildpack. You might want to take a look at this [apt buildpack](https://github.com/ddollar/heroku-buildpack-apt).

**Comment by jjb** [comment]
@dmathieu thanks for the detailed response! what I want to do is build an image to use with Vagrant for my local development. If Heroku started to build and host such an image, everyone would go nuts and cry tears of joy. but of course then you'd have to maintain/support it :)

**Comment by dmathieu** [comment]
The easiest way then might be to use our [docker base image](https://hub.docker.com/r/heroku/cedar/).

**Comment by jjb** [comment]
O_O
