### ISSUE TITLE
Question about local development for Heroku

### ISSUE THREAD

**Issue by davesque** [heroku/stack-images#6]
Is there any way to use this repository to build a local dev setup for Heroku apps?  I can see there's a `Vagrantfile` and some scripts which seem to bootstrap the VM.  However, this repo seems to be geared towards another purpose.  How can I just end up with a local VM that's running my project?

**Comment by chrisRidgers** [comment]
similar, I'm currently learning the ins/ outs of Vagrant and thought it would be cool to setup a Vagrant machine mimicking the live stack my site runs on.

Ideally i'd treat the machine exactly like I treat Heroku, I'd push to it with Git, where it would run my build pack and compile my app to a slug.  Similar to how my Heroku setup works.

This way I can push there instead of Heroku in order to test the deployment of my app before I push to Heroku.

It's a good knowledge building exercise I think, and would integrate well with small teams of developers who are working on a single project.  Rather than pushing to the live domain to check if a feature is displaying correctly (and thus potentially compromise the environment for any other developers running similar checks) he can vagrant up and push to virtual machine instead.

**Comment by chrisRidgers** [comment]
https://github.com/progrium/dokku

I've been pointed over towards dokku on the heroku build forums.
https://discussion.heroku.com/t/vagrant-box-local-development/1052/5

It looks interesting, can someone confirm how valid a Dokku Vagrant box would be as a testing platform?  Would it hold up when I push an application to my Heroku live sites?

**Comment by nruth** [comment]
I've ended up here a couple of times via google when looking for heroku compatible vagrant images for local development, and it's definitely confusing that the readme doesn't say what it is and isn't for, since there's a vagrant file.

**Comment by chrisRidgers** [comment]
I've still yet to find a perfect install.  Dokku looks like it fits the bill but then my build fails.

**Comment by friism** [comment]
We've recently [published a CLI plugin](https://blog.heroku.com/archives/2015/5/5/introducing_heroku_docker_release_build_deploy_heroku_apps_with_docker) that enables local dev and deploy using Docker tools.

We're working on improvements, [sign up for the beta to get updates](https://beta.heroku.com/docker-local-dev).

**Comment by chrisRidgers** [comment]
Gotta be said.  That looks very cool.
